rem execute
rem FOR %%i IN (".\data\*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\.csv"
rem FOR %%i IN (".\data\2015Y1S2 Mindset Survey - Prachatipat - SCI.PDF*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Mindset Survey - Prachatipat - SCI.PDF.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Samaedam - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Samaedam - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Weru - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Weru - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Trai - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Trai - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Trai - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Trai - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Trai - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Trai - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Suttaram - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Suttaram - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Suttaram - Math*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Suttaram - Math.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Sai - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Sai - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Sangkaracha - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Sangkaracha - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Samngam - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Samngam - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Samngam - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Samngam - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Samngam - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Samngam - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Rangbua - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Rangbua - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Rangbua - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Rangbua - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Pathum - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Pathum - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Pathum - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Pathum - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Matchun - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Matchun - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Matchan - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Matchan - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Ladpladuk - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Ladpladuk - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Koh - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Koh - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Angkaew - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Angkaew - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Thainiyom - SCI.PDF*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Thainiyom - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Thainiyom - MATH.PDF*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Thainiyom - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Thainiyom - ENG.PDF*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Thainiyom - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Thairath - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Thairath - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Thairath - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Thairath - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Thairath - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Thairath - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Sena - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Sena - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Sena - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Sena - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Sena - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Sena - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Puranawas - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Puranawas - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Prachatipat - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Prachatipat - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Prachatipat - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Prachatipat - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Pianpin - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Pianpin - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Naluang - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Naluang - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Loysai - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Loysai - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Loysai - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Loysai - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Keha - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Keha - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Keha - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Keha - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Kanthong - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Kanthong - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Choomchonmooban - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Choomchonmooban - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Choomchonmoban - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Choomchonmoban - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Choomchonmooban - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Choomchonmooban - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Chimplee - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Chimplee - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Chimplee - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Chimplee - ENG.csv"
FOR %%i IN (".\data\2015Y1S2 Mindset Survey - Wat Samaedum - SCI*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Mindset Survey - Wat Samaedum - SCI.csv"
FOR %%i IN (".\data\2015Y1S2 Student Mindset - Wat Bangpakok - MATH*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Student Mindset - Wat Bangpakok - MATH.csv"
FOR %%i IN (".\data\2015Y1S2 Mindset Survey - Wat Bangpakok - ENG*.jpg") DO .\Release\PollReader.exe "%%i" null ".\result\2015Y1S2 Mindset Survey - Wat Bangpakok - ENG.csv"
